sudo: false

language: python
python:
  - "2.7"

cache:
  apt: true
  pip: true
  directories:
    - $HOME/download-cache

before_install:
  - mkdir -p $HOME/download-cache

install:
  - pip install tox

env:
  - TOX_ENV=flake8

script:
  - tox -e $TOX_ENV
