sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

cache:
  apt: true
  pip: true
  directories:
    - $HOME/download-cache

before_install:
  - mkdir -p $HOME/download-cache

install:
  - pip install tox

script:
  - tox
